#!/bin/sh
#
# @name Custom Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Monkin <monkinsmurf@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15

